@startuml

title __PRINCIPLES's Class Diagram__\n

  namespace com.ion.training.oops.principles {
    class com.ion.training.oops.principles.CashPayment {
        + pay()
    }
  }
  

  namespace com.ion.training.oops.principles {
    class com.ion.training.oops.principles.CreditPayment {
        + pay()
    }
  }
  

  namespace com.ion.training.oops.principles {
    class com.ion.training.oops.principles.DebitPayment {
        + pay()
    }
  }
  

  namespace com.ion.training.oops.principles {
    class com.ion.training.oops.principles.Netbanking {
        + pay()
    }
  }
  

  namespace com.ion.training.oops.principles {
    interface com.ion.training.oops.principles.Payment {
        {abstract} + pay()
    }
  }
  

  namespace com.ion.training.oops.principles {
    class com.ion.training.oops.principles.PaymentFactory {
        {static} ~ createPayment()
    }
  }
  

  namespace com.ion.training.oops.principles {
    enum PaymentOptions {
      CASH
      CREDIT
      DEBIT
      NETBANKING
    }
  }
  

  namespace com.ion.training.oops.principles {
    class com.ion.training.oops.principles.PaymentTest {
        {static} + main()
    }
  }
  

  com.ion.training.oops.principles.CashPayment .up.|> com.ion.training.oops.principles.Payment
  com.ion.training.oops.principles.CreditPayment .up.|> com.ion.training.oops.principles.Payment
  com.ion.training.oops.principles.DebitPayment .up.|> com.ion.training.oops.principles.Payment
  com.ion.training.oops.principles.Netbanking .up.|> com.ion.training.oops.principles.Payment


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
